apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-webserver
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: go-webserver
  template:
    metadata:
      labels:
        app: go-webserver
    spec:
      containers:
      - image: go-webserver:latest
        name: go-webserver
        ports:
        - containerPort: 80